---
- name: RedHat/CentOS/Fedora/Amazon Linux | Install Filebeats repo
  yum_repository:
    name: khulnasoft_repo
    description: Khulnasoft Repo
    baseurl: "{{ filebeatrepo.yum }}"
    gpgkey: "{{ filebeatrepo.gpg }}"
    gpgcheck: true
  changed_when: false
