khulnasoft_repo:
  apt: 'deb https://packages-dev.khulnasoft.com/staging/apt/ unstable main'
  yum: 'https://packages-dev.khulnasoft.com/staging/yum/'
  gpg: 'https://packages-dev.khulnasoft.com/key/GPG-KEY-WAZUH'
  key_id: '0DCFCA5547B19D2A6099506096B3EE5F29111145'
khulnasoft_winagent_config_url: "https://packages-dev.khulnasoft.com/staging/windows/khulnasoft-agent-{{ khulnasoft_agent_version }}-1.msi"
khulnasoft_winagent_package_name: "khulnasoft-agent-{{ khulnasoft_agent_version }}-1.msi"

certs_gen_tool_version: 4.8

# Url of certificates generator tool
certs_gen_tool_url: "https://packages-dev.khulnasoft.com/{{ certs_gen_tool_version }}/khulnasoft-certs-tool.sh"