- name: Generate certificates prior to converging
  hosts: localhost
  become: true
  become_user: root
  roles:
    # 1. Check packages
    - role: ../../roles/khulnasoft/check-packages
      become: no
      delegate_to: localhost
      run_once: true
    # 2. Generate certificates
    - role: ../../roles/khulnasoft/khulnasoft-indexer
      vars:
        generate_certs: true
        perform_installation: false
        instances:
          node1:
            name: khulnasoft-es01       # Important: must be equal to indexer_node_name.
            ip: "127.0.0.1"   # When unzipping, the node will search for its node name folder to get the cert.
            role: indexer
          node3:
            name: khulnasoft-mgr01
            ip: "127.0.0.1"
            role: khulnasoft
          node5:
            name: khulnasoft-dash01
            ip: "127.0.0.1"
            role: dashboard
  pre_tasks:
    - name: overview of cert configuration
      debug:
        var: khulnasoft_endpoint_list

- name: Converge
  hosts: localhost
  become: true
  become_user: root
  roles:
    # 1. Khulnasoft indexer
    - role: ../../roles/khulnasoft/khulnasoft-indexer
      vars:
        indexer_node_name: "khulnasoft-es01"
        single_node: true
    # 2. Managers
    - role: ../../roles/khulnasoft/ansible-khulnasoft-manager
    - role: ../../roles/khulnasoft/ansible-filebeat-oss
      vars:
        filebeat_node_name: "khulnasoft-mgr01"
        filebeat_output_indexer_hosts:
        - "localhost:9200"
    # 3. Khulnasoft dashboard
    - role: ../../roles/khulnasoft/khulnasoft-dashboard
      vars:
        dashboard_node_name: "khulnasoft-dash01"
  vars:
    instances:
      node1:
        name: khulnasoft-es01       # Important: must be equal to indexer_node_name.
        ip: "127.0.0.1"  # When unzipping, the node will search for its node name folder to get the cert.
        role: indexer
      node3:
        name: khulnasoft-mgr01
        ip: "127.0.0.1"
        role: khulnasoft
      node5:
        name: khulnasoft-dash01
        ip: "127.0.0.1"
        role: dashboard