---

- include_vars: ../../vars/repo_vars.yml

- include_vars: ../../vars/repo.yml
  when: packages_repository == 'production'

- include_vars: ../../vars/repo_pre-release.yml
  when: packages_repository == 'pre-release'

- include_vars: ../../vars/repo_staging.yml
  when: packages_repository == 'staging'

- name: Overlay khulnasoft_agent_config on top of defaults
  set_fact:
    khulnasoft_agent_config: '{{ khulnasoft_agent_config_defaults | combine(config_layer, recursive=True) }}'
  vars:
    config_layer: '{{ khulnasoft_agent_config | default({}) }}'
  when: khulnasoft_agent_config_overlay | bool

- include_tasks: "Windows.yml"
  when: ansible_os_family == "Windows"

- include_tasks: "Linux.yml"
  when: ansible_system == "Linux"
