---
- name: RedHat/CentOS 5 | Install Khulnasoft repo
  yum_repository:
    name: khulnasoft_repo
    description: Khulnasoft repository
    baseurl: "{{ khulnasoft_agent_config.repo.yum }}5/"
    gpgkey: "{{ khulnasoft_agent_config.repo.gpg }}-5"
    gpgcheck: true
  changed_when: false
  when:
    - (ansible_facts['os_family']|lower == 'redhat') and (ansible_distribution|lower != 'amazon')
    - (ansible_distribution_major_version|int <= 5)
    - not khulnasoft_agent_sources_installation.enabled
    - not khulnasoft_custom_packages_installation_agent_enabled
  register: repo_v5_installed

- name: RedHat/CentOS/Fedora | Install Khulnasoft repo
  yum_repository:
    name: khulnasoft_repo
    description: Khulnasoft repository
    baseurl: "{{ khulnasoft_agent_config.repo.yum }}"
    gpgkey: "{{ khulnasoft_agent_config.repo.gpg }}"
    gpgcheck: true
  changed_when: false
  when:
    - repo_v5_installed is skipped
    - not khulnasoft_agent_sources_installation.enabled
    - not khulnasoft_custom_packages_installation_agent_enabled

- name: RedHat/CentOS/Fedora | Install OpenJDK 1.8
  yum: name=java-1.8.0-openjdk state=present
  when:
    - khulnasoft_agent_config.cis_cat.disable == 'no'
    - khulnasoft_agent_config.cis_cat.install_java == 'yes'
  tags:
    - init

- name: Set Distribution CIS filename for RHEL5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set Distribution CIS filename for RHEL7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Set Distribution CIS filename for RHEL7 (Amazon)
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "NA"

- name: RedHat/CentOS/RedHat | Install openscap
  package: name=openscap-scanner state=present
  register: khulnasoft_agent_openscap_package_install
  until: khulnasoft_agent_openscap_package_install is succeeded
  when: khulnasoft_agent_config.openscap.disable == 'no'
  tags:
    - init
