---
galaxy_info:
  author: Khulnasoft
  description: Installing and maintaining Khulnasoft indexer.
  company: khulnasoft.com
  license: license (GPLv3)
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - web
    - system
    - monitoring
